config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/failure'

  root to: "home#index"
  devise_for :users
  resources :books, :users
  get "books", to: "books#index"
  get "books/new", to: "books#new"
  resources :users, only: [:index, :show] do
    resources :books, only: [:new, :create, :edit, :update], shallow: true
  end
  
  get   '/login', :to => 'sessions#new', :as => :login
  match '/auth/:provider/callback', :to => 'sessions#create', :via => [:get]
  match '/auth/failure', :to => 'sessions#failure',  :via => [:get]

  resources :follows, only: [:create, :destroy]
end

app/models/book.rb
# == Schema Information
#
# Table name: books
#
#  id          :integer          not null, primary key
#  title       :string(255)
#  author      :string(255)
#  description :string(255)
#  amazon_id   :string(255)
#  rating      :integer
#  finished_on :date
#  created_at  :datetime
#  updated_at  :datetime
#

class Book < ActiveRecord::Base

  has_many :book_genres
  has_many :genres, through: :book_genres

  scope :finished, ->{ where.not(finished_on: nil) }
  scope :recent, ->{ where('finished_on > ?', 2.days.ago) }
  scope :search, ->(keyword){ where('keywords LIKE ?', "%#{keyword.downcase}%") if keyword.present? }
  scope :filter, ->(name){
    joins(:genres).where('genres.name = ?', name) if name.present?
  }

  before_save :set_keywords

  def finished?
    finished_on.present?
  end

  protected
    def set_keywords
      self.keywords = [title, author, description].map(&:downcase).join(' ')
    end
end

app/models/book_genre.rb
# == Schema Information
#
# Table name: book_genres
#
#  id         :integer          not null, primary key
#  created_at :datetime
#  updated_at :datetime
#

class BookGenre < ActiveRecord::Base
  belongs_to :book
  belongs_to :genre
end

app/models/follow.rb
# == Schema Information
#
# Table name: follows
#
#  id          :integer          not null, primary key
#  follower_id :integer
#  followed_id :integer
#  created_at  :datetime
#  updated_at  :datetime
#

class Follow < ActiveRecord::Base
    belongs_to :follower, class_name: :User, foreign_key: :follower_id
    belongs_to :followed, class_name: :User, foreign_key: :followed_id
end

app/models/genre.rb
# == Schema Information
#
# Table name: genres
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Genre < ActiveRecord::Base
  has_many :book_genres
  has_many :books, through: :book_genres
end

app/models/quit.rb
# == Schema Information
#
# Table name: quits
#
#  id         :integer          not null, primary key
#  text       :text
#  created_at :datetime
#  updated_at :datetime
#  user_id    :integer
#

class Quit < ActiveRecord::Base
  belongs_to :user

  validates :text, presence: true
  validates :user_id, presence: true
end

app/models/reading.rb
# == Schema Information
#
# Table name: readings
#
#  id         :integer          not null, primary key
#  text       :text
#  created_at :datetime
#  updated_at :datetime
#  user_id    :integer
#

class Reading < ActiveRecord::Base
  belongs_to :user

  validates :text, presence: true
  validates :user_id, presence: true
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime
#  updated_at             :datetime
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.includes(:genres).
      search(params[:keyword]).filter(params[:filter])
    @genres = Genre.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
        format.js
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :author,
                                   :description, :amazon_id,
                                   { genre_ids: []}, :rating)
    end
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
    def create
        followed = User.find(params[:user_id])
        follower = current_user
        Follow.create(follower: follower, followed: followed)
        redirect_to user_path(followed)
    end
    
    def destroy
        followed = User.find(params[:user_id])
        follower = current_user
        if follower == nil
            follow = Follow.where(followed_id: followed.id)
        else
            follow = Follow.where(followed_id: followed.id, follower_id: follower.id)
        end
        Follow.delete(follow)
        redirect_to user_path(followed)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
#    trainerless_pokemon = Pokemon.where(trainer:nil)
#    @pokemon = trainerless_pokemon.sample
  end

end

app/controllers/quits_controller.rb
class QuitsController < ApplicationController
  def new
    @user = User.find params[:user_id]
    @quit = @user.quits.build
  end

  def create
    @user = User.find params[:user_id]
    @quit = @user.quits.build quit_params
    if @quit.save
      redirect_to @quit.user
    else
      render "new"
    end
  end

  def edit
    @quit = Quit.find params[:id]
  end

  def update
    @quit = Quit.find params[:id]
    if @quit.update quit_params
      redirect_to @quit.user
    else
      render "edit"
    end
  end

  private

  def quit_params
    params.require(:quit).permit(:text)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	auth_hash = request.env['omniauth.auth']
  	render :text => auth_hash.inspect
  end

  def failure
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find params[:id]
    @follow = Follow.where(followed: @user, follower: current_user).first
  end

  def index
    @users = User.all
  end
    
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
  def image_from_amazon(amazon_id)
    image_tag "http://images.amazon.com/images/P/#{amazon_id}.01.ZTZZZZZZ.jpg"
  end
end

app/views/books/_book.html.erb
<li class="row rating-<%= book.rating %>" style="padding-top: 25px;">
  <div class="col-sm-3">
    <a href="#" target="_blank">
      <%= image_from_amazon(book.amazon_id) %>
    </a>
      </br></br>
      <span style="padding: 7%;">
      <% book.genres.each do |genre| %>
        <%= link_to genre.name, '#', class: 'label label-primary' %>
      <% end %>
    </span>
</br></br>
    <p class="text-center rating"><strong><%= book.rating %></strong>/5</p>
  </div>

  <div class="col-sm-9">
    <h3><a href="#"><%= book.title %></a></h3>
    <p ><em>Written by <%= book.author %></em></p>

    <div>
      <p style="color: #5db39d;">
        <%= book.description %>
      </p>
    </div>
    
      </br></br></br></br>
  </div>
</li>

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :amazon_id %><br>
    <%= f.text_field :amazon_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/books/create.js.erb
$('.book-list').prepend('<%=j render @book %>');
$('#new_book').trigger('reset');
$('.book-form').slideUp();

app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= render 'form' %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<style>
#grad1 {
    height:auto;
    background: url(img/downloads-bg.jpg) cover scroll no-repeat contain top center;
    background: -webkit-linear-gradient(#5db39d 5%, #a8e4d5 10%); /* For Safari 5.1 to 6.0 */
    background: -o-linear-gradient(#5db39d 5%, #a8e4d5 10%); /* For Opera 11.1 to 12.0 */
    background: -moz-linear-gradient(#5db39d 5%, #a8e4d5 10%); /* For Firefox 3.6 to 15 */
    background: linear-gradient(#5db39d 5%, #a8e4d5 10%); /* Standard syntax (must be last) */
}
</style>
<div class="container content-section text-center" id="grad1" style="padding-top:180px;">
  <h1 style="text-shadow: 2px 2px #888888;">Book List</h1>
  <ol class="breadcrumb">
    <li class="active">
      Books
    </li>
  </ol>
    <div style="float:right; width: 30%;">
      <div class='row'>
        <div class='col-sm-12'>
          <p>
            <form style="    padding-left: 15%;   padding-right: 15%;">
              <legend>Search</legend>
              <div>
                <input type='text' class='form-control' value='<%= params[:keyword] %>' name='keyword' placeholder='Keyword'  style="width: 100%;">
              </div>
            </form>
          </p>  
        </div>
      </div>

      <hr>
      <div class='col-sm-12 book-form'>
    <!--
          <p class='pull-right'>
            <a href='#' id='show-form' class='btn btn-primary'>New Book Form</a>
          </p>
    -->
        <p>
          <%= form_for(Book.new, remote: true,
                       html: { class: 'horizontal-form' }) do |f| %>
          <legend>New Book</legend>


    <!--    New Book Form    -->
          <div  style="align-self: auto; padding-left: 15%; padding-right: 15%;">
            <div class='form-group' style="width:100&" >

    <!--genre div-->

            <br>

            <div class='form-group'>
              <%= f.text_field :title, class: 'form-control', placeholder: 'Title' %>
            </div>
            <div class='form-group'>
              <%= f.text_field :author, class: 'form-control', placeholder: 'Author' %>
            </div>
            <div class='form-group'>
              <%= f.text_field :description, class: 'form-control', placeholder: 'Description' %>
            </div>
            <div class='form-group'>
              <%= f.text_field :amazon_id, class: 'form-control', placeholder: 'Amazon ID' %>
            </div>

            <div class='form-group'>
              <legend>rating</legend>
              <% (1..5).each do |rating| %>
                <label class='radio-inline'>
                  <%= rating %><%= f.radio_button :rating, rating %>
                </label>
              <% end %>
            </div>

            <div class='form-group'>
              <%= f.submit class: 'btn btn-primary' %>
            </div>
          </div>
          <% end %>
        </p>
      </div>
    </div>
</div>


  <div class="row">
    <div class="col-sm-8">
      <ul class="list-unstyled book-list">

        <%= render @books %>
         
      </ul>
    </div>
    <div class="col-sm-4" >
      <h2>Genres</h2>
      <ul class="list-unstyled">
        <% @genres.each do |genre| %>
          <li>
            <%= link_to genre.name, books_path(filter: genre.name),
              class: 'label label-primary' %>
          </li>
        <% end %>
      </ul>
    </div>
      </br>
  </div>

app/views/books/new.html.erb
<h1>New book</h1>

<%= render 'form' %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<!-- <p id="notice"><%= notice %></p>
 -->
<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Author:</strong>
  <%= @book.author %>
</p>

<p>
  <strong>Description:</strong>
  <%= @book.description %>
</p>

<p>
  <strong>Amazon:</strong>
  <%= @book.amazon_id %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/books/tem/edit.html.slim
h1 Editing book

== render 'form'

= link_to 'Show', @book
'|
= link_to 'Back', books_path

app/views/books/tem/index.html.slim
h1 Listing books

table
  thead
    tr
      th Title
      th Author
      th Description
      th Amazon
      th Rating
      th Finished on
      th
      th
      th

  tbody
    - @books.each do |book|
      tr
        td = book.title
        td = book.author
        td = book.description
        td = book.amazon_id
        td = book.rating
        td = book.finished_on
        td = link_to 'Show', book
        td = link_to 'Edit', edit_book_path(book)
        td = link_to 'Destroy', book, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Book', new_book_path

app/views/home/index.html.erb
 <%= render 'layouts/content' %>

app/views/layouts/_content.html.erb
   <!-- Intro Header -->
    <header class="intro">
        <div class="intro-body">
            <div class="container">
                <div class="row">
                    <div class="col-md-8 col-md-offset-2">
                        </br>
                        <h1 class="brand-heading">the Joy Reading Club</h1>
                        <p class="intro-text">A place to share your reading with others.</p>
                        <a href="#about" class="btn btn-circle page-scroll">
                            <i class="fa fa-angle-double-down animated"></i>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <!-- About Section -->
    <section id="about" class="container content-section text-center">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2">
                <h2>About the Joy Reading Club</h2>
                <p>Like reading books? This is a perfect place for you! You can comment on books, keep track of the books you read, and share with others. 
                    <p>Join our community right now!</p>
                <p>This is version 1.0, but more functions are coming up soon!</p>
            </div>
        </div>
    </section>

    <!-- browse Section -->
    <section id="browse" class="content-section text-center">
        <div class="browse-section">
            <div class="container">
                <div class="col-lg-8 col-lg-offset-2">
                    <h2>Browse Books</h2>
                    <p>You can start from browsing books in the Joy Reading Club.</p>
                    <li class="btn btn-default btn-lg"><%= link_to "Visit Browse Page", books_path%></li>
                </div>
            </div>
        </div>
    </section>

    <!-- Contact Section -->
    <section id="contact" class="container content-section text-center">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2">
                <h2>Contact the Club</h2>
                <p>Feel free to email us to provide some feedback on our website, give us suggestions for new functions, or to just say hello!</p>
                <p><a href="mailto:thisisreallyaname@gmail.com">Email us here!</a>
                </p>
                <ul class="list-inline banner-social-buttons">
                    <li>
                        <a href="https://twitter.com/Amber44Summer" class="btn btn-default btn-lg"><i class="fa fa-twitter fa-fw"></i> <span class="network-name">Twitter</span></a>
                    </li>
                    <li>
                        <a href="https://github.com/lentebloem" class="btn btn-default btn-lg"><i class="fa fa-github fa-fw"></i> <span class="network-name">Github</span></a>
                    </li>
                    <li>
                        <a href="https://plus.google.com/+thisisreallyaname/posts" class="btn btn-default btn-lg"><i class="fa fa-google-plus fa-fw"></i> <span class="network-name">Google+</span></a>
                    </li>
                </ul>
            </div>
        </div>
    </section>

    <!-- Map Section -->
    <div id="map"></div>

app/views/layouts/greyscale/application.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>The Joy Reading Club</title>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

    <!-- Bootstrap Core CSS -->
     <%= stylesheet_link_tag    'bootstrap.min.css', media: 'all', 'data-turbolinks-track' => true %>
       <!-- Custom CSS -->
    <%= stylesheet_link_tag    'grayscale.css', media: 'all', 'data-turbolinks-track' => true %>


    <!-- Custom Fonts -->
    <link href="font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body id="page-top" data-spy="scroll" data-target=".navbar-fixed-top">

    <!-- Navigation -->
    <nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
                    <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand page-scroll" href="#page-top">
                    <i class="fa fa-play-circle"></i> the Joy <span class="light">Reading</span> Club
                </a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
                <ul class="nav navbar-nav">
                    <!-- Hidden li included to remove active class from about link when scrolled up past about section -->
                    <li class="hidden">
                        <a href="#page-top"></a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#about">About</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#browse">Browse</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#contact">Contact</a>
                    </li>
                   <li>
                        <a class="page-scroll" href="login">Log in</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Intro Header -->
    <header class="intro">
        <div class="intro-body">
            <div class="container">
                <div class="row">
                    <div class="col-md-8 col-md-offset-2">
                        <h1 class="brand-heading">the Joy Reading Club</h1>
                        <p class="intro-text">A place to share your reading with others.</p>
                        <a href="#about" class="btn btn-circle page-scroll">
                            <i class="fa fa-angle-double-down animated"></i>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <!-- About Section -->
    <section id="about" class="container content-section text-center">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2">
                <h2>About the Joy Reading Club</h2>
                <p>Like reading books? This is a perfect place for you! You can comment on books, keep track of the books you read, and share with others. 
                    <p>Join our community right now!</p>
                <p>This is version 1.0, but more functions are coming up soon!</p>
            </div>
        </div>
    </section>

    <!-- browse Section -->
    <section id="browse" class="content-section text-center">
        <div class="browse-section">
            <div class="container">
                <div class="col-lg-8 col-lg-offset-2">
                    <h2>Browse Books</h2>
                    <p>You can start from browsing books in the Joy Reading Club.</p>
                    <li class="btn btn-default btn-lg"><%= link_to "Visit Browse Page", books_path%></li>
                </div>
            </div>
        </div>
    </section>

    <!-- Contact Section -->
    <section id="contact" class="container content-section text-center">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2">
                <h2>Contact the Club</h2>
                <p>Feel free to email us to provide some feedback on our website, give us suggestions for new functions, or to just say hello!</p>
                <p><a href="mailto:thisisreallyaname@gmail.com">Email us here!</a>
                </p>
                <ul class="list-inline banner-social-buttons">
                    <li>
                        <a href="https://twitter.com/Amber44Summer" class="btn btn-default btn-lg"><i class="fa fa-twitter fa-fw"></i> <span class="network-name">Twitter</span></a>
                    </li>
                    <li>
                        <a href="https://github.com/lentebloem" class="btn btn-default btn-lg"><i class="fa fa-github fa-fw"></i> <span class="network-name">Github</span></a>
                    </li>
                    <li>
                        <a href="https://plus.google.com/+thisisreallyaname/posts" class="btn btn-default btn-lg"><i class="fa fa-google-plus fa-fw"></i> <span class="network-name">Google+</span></a>
                    </li>
                </ul>
            </div>
        </div>
    </section>

    <!-- Map Section -->
    <div id="map"></div>

    <!-- Footer -->
    <footer>
        <div class="container text-center">
            <p>Copyright &copy; the Joy Reading Club 2015</p>
        </div>
    </footer>

    <!-- jQuery -->
    <script src="js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="js/bootstrap.min.js"></script>

    <!-- Plugin JavaScript -->
    <script src="js/jquery.easing.min.js"></script>

    <!-- Google Maps API Key - Use your own API key to enable the map feature. More information on the Google Maps API can be found at https://developers.google.com/maps/ -->
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCRngKslUGJTlibkQ3FkfTxj3Xss1UlZDA&sensor=false"></script>

    <!-- Custom Theme JavaScript -->
    <script src="js/grayscale.js"></script>

</body>

</html>

app/views/layouts/temp/application.html.slim
doctype html
html
  head
    title Killer-diller
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    .container
      .header
        ul.nav.nav-pills.pull-right
          li = link_to "Home", root_path
        h3.text-muted Killer Diller
      = yield

app/views/quits/edit.html.slim
h1 Editing Quit

= simple_form_for @quit do |f|
  = f.input :text
  = f.button :submit

app/views/quits/new.html.slim
h1 Creating Quit for #{@user.name}

= simple_form_for [@user, @quit] do |f|
  = f.input :text
  = f.button :submit

app/views/readings/edit.html.slim
h1 Editing Reading

= simple_form_for @quit do |f|
  = f.input :text
  = f.button :submit

app/views/readings/new.html.slim
h1 Creating Reading for #{@user.name}

= simple_form_for [@user, @quit] do |f|
  = f.input :text
  = f.button :submit

app/views/users/index.html.erb
h1 Users

- @users.each do |user|
  h2 = link_to user.name, user
  h4 Has #{pluralize user.quits.count, "post"}

app/views/users/show.html.slim
h1 #{@user.name} #{link_to "+", new_user_quit_path(@user)}
- if @follow
  = link_to "Unfollow", follow_path(user_id: @user.id), method: :delete
- elsif current_user != @user
  = link_to "Follow", follows_path(user_id: @user.id), method: :post

h3 Posts

- @user.quits.each do |quit|
    h4 = link_to quit.text, edit_quit_path(quit)

h3
    | Who I follow
    - @user.followed_users.each do |u|
      h4 = link_to u.name, user_path(u)
      